name: 'Automatic pipeline generator'
description: 'Used to generate an opinionated GitHub workflow'
inputs:
  packages_to_install:
    description: 'Packages to install'
    required: false
  docker_image_to_use:
    description: 'Docker image to use'
    required: false
  item_to_build:
    description: 'File to use when detecting the tech to build'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.packages_to_install-file }}
    - ${{ inputs.docker_image_to_use }}
branding:
  icon: 'git-commit'
  color: 'green'
